# Generated by Django 4.0.3 on 2022-04-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('SUV', 'Sport Utility Vehicle'), ('MPV', 'Multi Purpose Vehicle'), ('ECO', 'Eco Car'), ('HEV', 'Hybrid Electric Vehicles'), ('EV', 'Electric Vehicles'), ('PU', 'Pick-Up Truck'), ('VAN', 'Van Car'), ('SED', 'Sedan'), ('SUP', 'Supercar'), ('COP', 'Coupe')], max_length=3)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('NO_AVAILABLE', 'Reserved')], max_length=25)),
                ('image', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('miles', models.IntegerField()),
                ('price', models.IntegerField()),
                ('about', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name', 'location'],
            },
        ),
    ]
